package com.softwaremill.slackit.webapi.model.users

case class Member(id: String,
                  team_id: String,
                  name: String,
                  deleted: Boolean,
                  status: Option[String],
                  color: Option[String],
                  real_name: Option[String],
                  tz: Option[String],
                  tz_label: Option[String],
                  tz_offset: Option[Int],
                  profile: Profile,
                  is_admin: Option[Boolean],
                  is_owner: Option[Boolean],
                  is_primary_owner: Option[Boolean],
                  is_restricted: Option[Boolean],
                  is_ultra_restricted: Option[Boolean],
                  is_bot: Boolean,
                  has_2fa: Option[Boolean],
                  two_factor_type: Option[String],
                  presence: Option[String])

case class Profile(avatar_hash: Option[String],
                   first_name: Option[String],
                   last_name: Option[String],
                   real_name: Option[String],
                   email: Option[String],
                   skype: Option[String],
                   phone: Option[String],
                   image_24: String,
                   image_32: String,
                   image_48: String,
                   image_72: String,
                   image_192: String,
                   image_512: Option[String],
                   image_1024: Option[String],
                   image_original: Option[String])
